# Generated by Django 4.2.1 on 2023-05-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicated_product',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('formative_group', models.CharField(max_length=50, verbose_name='Фармакологическая группа')),
                ('pharmaceutical_form', models.CharField(max_length=15, verbose_name='Лекарственная форма')),
                ('dosage', models.CharField(max_length=30, verbose_name='Дозировка')),
                ('volume_in_package', models.CharField(max_length=15, verbose_name='Количество в упаковке')),
                ('sales_condition', models.CharField(max_length=50, verbose_name='Условия отпуска')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('shelf_life', models.PositiveIntegerField(verbose_name='Срок годности')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
            ],
        ),
    ]
