# Generated by Django 4.2.1 on 2023-05-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_medicated_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_medicated_product',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('volume_in_package', models.CharField(max_length=15, verbose_name='Количество в упаковке')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('shelf_life', models.PositiveIntegerField(null=True, verbose_name='Срок годности')),
                ('guarantee', models.PositiveIntegerField(null=True, verbose_name='Срок гарантии')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
            ],
        ),
    ]
