# Generated by Django 4.2.1 on 2023-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_non_medicated_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicated_product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='non_medicated_product',
            name='guarantee',
            field=models.PositiveIntegerField(blank=999, null=True, verbose_name='Срок гарантии'),
        ),
        migrations.AlterField(
            model_name='non_medicated_product',
            name='shelf_life',
            field=models.PositiveIntegerField(blank=999, null=True, verbose_name='Срок годности'),
        ),
    ]
