# Generated by Django 4.2.1 on 2023-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата и время')),
                ('till_number', models.PositiveIntegerField(verbose_name='Номер кассы')),
                ('pharmacist', models.CharField(max_length=50, verbose_name='ФИО фармацевта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма к оплате')),
            ],
        ),
    ]
