# Generated by Django 4.2.1 on 2023-05-24 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_non_medicated_product'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
        ),
    ]
