# Generated by Django 4.2.1 on 2023-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма к оплате'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='amount',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость'),
        ),
    ]
