# Generated by Django 4.2.1 on 2023-05-25 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_amount_alter_purchase_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5), django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
