# Generated by Django 4.2.1 on 2023-05-25 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
