# Generated by Django 4.2.1 on 2023-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchase_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
